#!/bin/bash

export MITIE_MODELS=../../../MITIE-models


run_default_params()
{
    THREADS="--threads=16"
    LOG=test_default.txt
    ./ner_conll --train-chunker eng.train_all_some_sentences_combined $THREADS > $LOG
    ./ner_conll --train-id      eng.train_all_some_sentences_combined $THREADS >> $LOG

    ./ner_conll --test-id eng.testb >> $LOG
    ./ner_conll --tag-conll-file ner_model.dat eng.testb | ./conlleval 
    echo $LOG
    tail -n1 $LOG 
}

run_default_params
