/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.mit.ll.mitie;

public class NerTrainer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected NerTrainer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NerTrainer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        globalJNI.delete_NerTrainer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public NerTrainer(String filename) {
    this(globalJNI.new_NerTrainer(filename), true);
  }

  public void add(NerTrainingInstance item) {
    globalJNI.NerTrainer_add(swigCPtr, this, NerTrainingInstance.getCPtr(item), item);
  }

  public void setThreadNum(long num) {
    globalJNI.NerTrainer_setThreadNum(swigCPtr, this, num);
  }

  public void train(String filename) {
    globalJNI.NerTrainer_train(swigCPtr, this, filename);
  }

  public void trainSeparateModels(String filename) {
    globalJNI.NerTrainer_trainSeparateModels(swigCPtr, this, filename);
  }

}
