/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.mit.ll.mitie;

public class SWIGTYPE_p_mitie__binary_relation {
  private long swigCPtr;

  protected SWIGTYPE_p_mitie__binary_relation(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_mitie__binary_relation() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_mitie__binary_relation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

