/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.mit.ll.mitie;

import java.io.IOException;
import java.util.Objects;

public class TotalWordFeatureExtractor {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TotalWordFeatureExtractor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TotalWordFeatureExtractor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        globalJNI.delete_TotalWordFeatureExtractor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TotalWordFeatureExtractor(String filename) {
    this(globalJNI.new_TotalWordFeatureExtractor(filename), true);
  }
  private static TotalWordFeatureExtractor englishExtractor;

  public static TotalWordFeatureExtractor getEnglishExtractor() {
    if (Objects.isNull(englishExtractor)) {
      try {
        String tempExtractorPath = NativeUtils.getTempPathFromJar("/extractors/english/total_word_feature_extractor.dat");
        englishExtractor = new TotalWordFeatureExtractor(tempExtractorPath);
      } catch (IOException e) {
        e.printStackTrace();
      }
    }

    return englishExtractor;
  }

}
